version: '3'

services:
  base:
    build:
      context: ./api/
      dockerfile: ./base.dockerfile
      args:
        BUILD_ENV : ${FAAS_BUILD_ENV}
    image: faas/base

  api:
    build:
      context: ./api/
      dockerfile: ./api.dockerfile
      args:
        BUILD_ENV : ${FAAS_BUILD_ENV}
    image: faas/api
    hostname: api
    env_file:
      - ./config/${FAAS_BUILD_ENV}.env
    ports:
      - "8090:8090"
    depends_on:
      - database
      - migrate

  migrate:
    build:
      context: ./api/
      dockerfile: ./migrate.dockerfile
      args:
        BUILD_ENV : ${FAAS_BUILD_ENV}
    image: faas/migrate
    env_file:
      - ./config/${FAAS_BUILD_ENV}.env

  database:
    image: postgres
    hostname: database
    env_file:
      - ./config/${FAAS_BUILD_ENV}.env
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"

  worker-nodejs:
    build:
      context: ./worker-nodejs/
      dockerfile: ./worker.dockerfile
      args:
        BUILD_ENV : ${FAAS_BUILD_ENV}
    image: faas/worker-nodejs
    env_file:
      - ./config/${FAAS_BUILD_ENV}.env
    depends_on:
      - api
  
  worker-reactjs:
    build:
      context: ./worker-reactjs/
      dockerfile: ./worker.dockerfile
      args:
        BUILD_ENV : ${FAAS_BUILD_ENV}
    image: faas/worker-reactjs
    env_file:
      - ./config/${FAAS_BUILD_ENV}.env
    depends_on:
      - api

  envoy:
    build:
      context: ./envoy/
      dockerfile: ./envoy.dockerfile
      args:
        BUILD_ENV: ${FAAS_BUILD_ENV}
    image: faas/envoy
    ports:
      - "80:80"
    depends_on:
      - api
